### ISSUE TITLE
Improve the root cause analysis message for a new shell

### ISSUE THREAD

**Issue by aperepel** [sequenceiq/cloudbreak-deployer#59] opened 2015-05-18 18:00 UTC
```bash
01:56:35::cbd-first ♨ >  DEBUG=1 cbd ps
[DEBUG] Use profile: Profile
[DEBUG] CloudBreak Deployer 0.5.0
[DEBUG] docker-compose -p cbreak ps
Couldn't connect to Docker daemon - you might need to run `boot2docker up`.
```

The boot2docker is up and running and what really has to be done is init the shell to point to the docker process in the vm, like below:

```
01:56:38::cbd-first ♨ >  eval $(boot2docker shellinit)
```

**Comment by lalyos** [comment] 2015-05-18 18:13
Good point, root cause analysis is important indeed! We created a special command: `cbd doctor`
Influenced by `brew doctor`

Could you please check if it would advise the correct solution?

**Comment by aperepel** [comment] 2015-05-18 19:37
To keep things in one place (here :) ). The `cbd doctor` does complain, but without prompting for any resolution:

```
♨ >  cbd doctor
===> Deployer doctor: Checks your environment, and reports a diagnose.
local version:0.5.1
latest release:0.5.1
boot2docker date settings: OK
boot2docker: OK
docker command: OK
docker client version: OK
[ERROR] docker version returned an error
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): darwin/amd64
time="2015-05-18T15:35:57-04:00" level=fatal msg="Get http:///var/run/docker.sock/v1.18/version: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?"
```

**Comment by lalyos** [comment] 2015-05-18 19:49
I'm trying to rely on `boot2docker shellinit` output to give a hint.
I remember that in previous versions were writing "Your environment variables are already set correctly." to stdout, and no "export DOCKER_XXX". So a simple
```
if [[ "$(boot2docker shelling 2>/dev/null)" == "" ]]; then
  # ok
else
  # give hint to run boot2docker shellinit
fi
```
Would make a perfect solution.

Unfortunately `boot2docker shellinit` **always** writes the `export DOCKER_XXX` instructions regardless, if they are already set.

## Pull Request

I issued a pull request to fix it: https://github.com/boot2docker/boot2docker-cli/pull/366

Until it gets merged I'm fixing it by reimplementing the checkEnvironment() call [sees original go function](https://github.com/lalyos/boot2docker-cli/blob/add-checkEnvironment-into-shellinit/cmds.go#L190)

**Closed** 2015-05-18 20:09 UTC

**Comment by lalyos** [comment] 2015-05-18 20:11
Its automatically closed by the commit message. 

Please check `cbd doctor` after `cbd update master` and reopen if it doesn't give you the correct hint.
After that please go back to latest released version with `cbd update`
