### ISSUE TITLE
Cloudbreak deployer create cluster issue

### ISSUE THREAD

**Issue by verstrae** [sequenceiq/cloudbreak-deployer#47] opened 2015-05-06 11:10 UTC
When creating a cluster in the cloudbreaker-ui using AWS credentials with default/advanced settings, no cluster is created when pressing the create-cluster button.

No data appears in the logs (cbd logs) when trying to execute

cloudbreak is running on the boot2docker vm 

Boot2Docker version output
-------------------------------------
Boot2Docker-cli version: v1.6.0
Git commit: 9894ae9

cbd doctor output
------------------------
boot2docker: OK
docker command: OK
docker client version: OK
docker server version: OK
Everything is very-very first class !!!

cbd version output
-------------------------
0.1.0
latest version:
0.1.0

**Comment by malathit90** [comment] 2015-05-25 05:36
Check if there are issues with your browser. Few days back with Firefox browser I had the same problem. When checked in firefox console, there was an error with javascript. 

Right now the problem is resolved in firefox as well in the latest version. Hope updating to the latest version will help.

**Comment by lalyos** [comment] 2015-09-09 17:58
closing outdated cbd issue. please reopen if it still happens with latest version.

**Closed by lalyos** 2015-09-09 17:58 UTC
