### ISSUE TITLE
cbd pull/start hangs trying to pull sequenceiq/ambassadord:0.5.0

### ISSUE THREAD

**Issue by jalkjaer** [sequenceiq/cloudbreak-deployer#126] opened 2015-09-10 10:39 UTC
The sequenceiq/ambassadord [docker hub page](https://hub.docker.com/r/sequenceiq/ambassadord/builds/) doesn't have an attached Dockerfile, and the source link goes to 
https://github.com/sequenceiq/connectable 
So its not really clear if they in fact are the same
(I can pull other images from docker hub just fine)

**Comment by lalyos** [comment] 2015-09-21 11:01
Hi @jalkjaer 

The issue is based on the movement/changes on the forked repo:
- originally it was: http://github.com/progrium/ambassadord
- which became: github.com/gliderlabs/connectable

But meanwhile the branches are moved/renamed as well.

The strange thing is that I have a 'sequenceiq/ambassadord:0.5.0' with the age of: **11 weeks ago**.
Anyway:
- I'm trying to fix the docker hub tag (in process)
- But we have already eliminated ambassadord from our cloudbreak deployment (we had some strange issues, connections via ambassadord where refused)

So the next release of cloudbreak/deployer won't use ambassador.

**Comment by lalyos** [comment] 2015-09-21 12:08
It seems that this issue is related with the docker hub 2.0 introduction.

We have the same `sequenceiq/ambassadord:0.5.0` image with the same image id: `c47190cf08ba`,
on all dev env as well as prepared, prod, qa ...

So dockerhub definitely served this imaged a couple of weeks ago. We have opened a support issue, so docker hub might be able to recover the 0.5.0 tag.

**Comment by lalyos** [comment] 2015-09-21 12:47
Meanwhile i checked it on a new docker host. Although DockerHub shows it as 0bytes, you can still successfully pull it:

```
docker pull sequenceiq/ambassadord:0.5.0
0.5.0: Pulling from sequenceiq/ambassadord
428b411c28f0: Pull complete 
435050075b3f: Pull complete 
9fd3c8c9af32: Pull complete 
6d4946999d4f: Pull complete 
d161864d5423: Pull complete 
b39cfe4ace84: Pull complete 
4c2ab2cd54bc: Pull complete 
1a4bdb7ab0ad: Pull complete 
c47190cf08ba: Already exists 
Digest: sha256:5e75f17761bb4ab0ef71a3c0576b8fcf15053e0f4434d13c6c8f52a81c475d7d
Status: Downloaded newer image for sequenceiq/ambassadord:0.5.0
```

So seems that the image is at least in a gullible state, So i'm closing this issue. Please reopen if you still experience the pull issue.

**Closed by lalyos** 2015-09-21 12:47 UTC
